<div class="container">

    <?php if(!isset($contact)): ?>
        <form action="<?= \App::getBaseUrl(); ?>contact/add" method="post">
    <?php else: ?>
        <form action="<?= \App::getBaseUrl(); ?>contact/update" method="post">
    <?php endif; ?>

        <div>
            <?php if(!isset($contact)): ?>
                <h2>Neuer Kontakt</h2>
            <?php else: ?>
                <h2>Kontakt</h2>
            <?php endif; ?>
        </div>
        <div>
            <label for="name">Firma:</label>
            <input type="text" name="name" value="<?= isset($contact) ? $contact->getName() : ''; ?>" id="name">
        </div>
        <div>
            <label for="firstname">Vorname:</label>
            <input type="text" name="firstname" value="<?= isset($contact) ? $contact->getFirstname() : ''; ?>" id="firstname">
            <label for="lastname">Nachname:</label>
            <input type="text" name="lastname" value="<?= isset($contact) ? $contact->getLastname() : ''; ?>" id="lastname">
        </div>
        <fieldset><legend>Adresse</legend>
            <div>
                <label for="street">Straße:</label>
                <input type="text" name="street" id="street">
            </div>
            <div>
                <label for="zip">PLZ:</label>
                <input type="text" name="zip" id="zip">
            </div>
            <div>
                <label for="city">Ort:</label>
                <input type="text" name="city" value="<?= isset($contact) ? $contact->getcity() : ''; ?>" id="city">
            </div>
            <div>
                <label for="state">Bundesland:</label>
                <input type="text" name="state" id="state">
            </div>
            <div>
                <label for="country">Land:</label>
                <input type="text" name="country" id="country">
            </div>
        </fieldset>
        <div>
            <label for="phone">Telefon:</label>
            <input type="text" name="phone" value="<?= isset($contact) ? $contact->getPhone() : ''; ?>" id="phone">
        </div>
        <div>
            <label for="mobile">Mobile:</label>
            <input type="text" name="mobile" id="mobile">
        </div>
        <div>
            <label for="email">Email:</label>
            <input type="email" name="email" id="email">
        </div>
        <div class="button-row">
            <button type="submit" class="button">Speichern</button>&nbsp;&nbsp;
            <button type="reset" class="button">Abbrechen</button>
        </div>
    </form>
</div>
