<div>
    <div>
        <h2>Kontakt</h2>
    </div>
    <div>
        <label for="name">Kontakt:</label>
        <span><?= $contact->getName(); ?></span>
    </div>
    <div>
        <label for="firstname">Vorname:</label>
        <span><?= $contact->getFirstname(); ?></span>
        <label for="lastname">Nachname:</label>
        <span><?= $contact->getLastname(); ?></span>
    </div>
    <div>
        <label for="city">Ort:</label>
        <span><?= $contact->getCity(); ?></span>
    </div>
    <div>
        <label for="phone">Telefon:</label>
        <span><?= $contact->getPhone(); ?></span>
    </div>
    <div>
        <label for="email">Email:</label>
        <span><?= $contact->getPhone(); ?></span>
    </div>
    <div class="button-row">
        <a class="button" href="<?= \App::getBaseUrl(); ?>contact/edit/id/<?= $contact->getId(); ?>">Bearbeiten</a>
    </div>
    <div class="container">
        <!-- Projektübersicht -->
        <div class="projects">
            <h2>Projektübersicht
                <span class="element-pos-right"><a class="button-light" href="<?= \App::getBaseUrl(); ?>project/new" title="Neue Aufgabe anlegen.">+</a></span>
                <hr>
            </h2>
            <?php if(isset($projects)): ?>
            <table>
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Projektname</th>
                        <th>Begin</th>
                        <th>Ende</th>
                        <th>Status</th>
                        <th>Erstellt am</th>
                        <th colspan="2">Aktionen</th>
                    </tr>
                </thead>
                <tbody id="projects-table">
                  <?php foreach($projects as $project): ?>
                      <tr class="clickable-row" data-href="<?= \App::getBaseUrl(); ?>project/view/id/<?= $project->getId(); ?>">
                          <td><?= $project->getId(); ?></td>
                          <td><?= $project->getTitle(); ?></td>
                          <td><?= $project->getBegin(); ?></td>
                          <td><?= $project->getEnd(); ?></td>
                          <td><?= $project->getStatus(); ?></td>
                          <td><?= $project->getCreatedAt(); ?></td>
                          <td class="action-button"><a href="<?= \App::getBaseUrl(); ?>project/edit/id/<?= $project->getId(); ?>">Bearbeiten</a></td>
                      </tr>
                  <?php endforeach; ?>
                </tbody>
            </table>
            <?php else: ?>
            <div>
                <p>Es wurden noch keine Projekte erstellt.</p>
                <div>
                    <a href="<?= \App::getBaseUrl(); ?>project/new" class="button">Anlegen</a>
                </div>
            </div>
            <?php endif; ?>
        </div>
        <!-- Projektübersicht -->
        <!-- Aufgabenübersicht -->
        <div class="tasks">
            <h2>Aufgabenübersicht
                <span class="element-pos-right"><a class="button-light" href="<?= \App::getBaseUrl(); ?>task/new" title="Neue Aufgabe anlegen.">+</a></span>
                <hr>
            </h2>
            <?php if(isset($tasks)): ?>
            <table>
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Titel</th>
                        <th>Projekt</th>
                        <th>Begin</th>
                        <th>Ende</th>
                        <th>Status</th>
                        <th colspan="2">Aktionen</th>
                    </tr>
                </thead>
                <tbody id="tasks-table">
                  <?php foreach($tasks as $task): ?>
                      <tr class="clickable-row" data-href="<?= \App::getBaseUrl(); ?>task/view/id/<?= $task->getId(); ?>">
                          <td><?= $task->getId(); ?></td>
                          <td><?= $task->getTitle(); ?></td>
                          <td><?= $task->getProjectTitle(); ?></td>
                          <td><?= $task->getBegin(); ?></td>
                          <td><?= $task->getEnd(); ?></td>
                          <td><?= $task->getStatus(); ?></td>
                          <td class="action-button"><a href="<?= \App::getBaseUrl(); ?>task/edit/id/<?= $task->getId(); ?>">Bearbeiten</a></td>
                      </tr>
                  <?php endforeach; ?>
                </tbody>
            </table>
            <?php else: ?>
            <div>
                <p>Es wurden noch keine Projekte erstellt.</p>
                <div>
                    <a href="<?= \App::getBaseUrl(); ?>task/new" class="button">Anlegen</a>
                </div>
            </div>
            <?php endif; ?>
        </div>
        <!-- Aufgabenübersicht -->
    </div>
</div>
