<!DOCTYPE html>
<html lang="de">
    <head>
        <meta charset="utf8">
        <title>Hauptseite</title>
        <link href="<?php echo \App::getBaseUrl(); ?>skin/css/style.css" rel="stylesheet">
    </head>
    <body>
        <nav>
            <ul class="navigation">
                <li><a href="<?php echo \App::getBaseUrl(); ?>index/main">Start</a></li>
                <li><a href="<?php echo \App::getBaseUrl(); ?>contact/index">Kontakte</a></li>
                <li><a href="<?php echo \App::getBaseUrl(); ?>project/index">Projekte</a></li>
                <li><a href="<?php echo \App::getBaseUrl(); ?>task/index">Aufgaben</a></li>
                <li>
                    <?php if(\Session\User::isLoggedIn()): ?>
                        <a href="<?php echo \App::getBaseUrl(); ?>index/login">Sign out</a>
                    <?php else: ?>
                        <a href="<?php echo \App::getBaseUrl(); ?>index/login">Sign in</a>
                    <?php endif; ?>
                </li>
            </ul>
        </nav>
        <header>
            <h1>Project-Planner</h1>
        </header>
        <!-- Kontaktübersicht -->
        <div>
            <h2>Kontaktübersicht</h2>
            <table>
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Firma</th>
                        <th>Ansprechpartner</th>
                        <th>Ort</th>
                        <th>Telefon</th>
                        <th colspan="3">Aktionen</th>
                    </tr>
                </thead>
                <tbody>
                  <?php foreach($contacts as $contact): ?>
                      <tr>
                          <td><?php echo $contact->getId(); ?></td>
                          <td><?php echo $contact->getName(); ?></td>
                          <td><?php echo $contact->getFirstname() . '&nbsp;'
                            . $contact->getLastname(); ?></td>
                          <td><?php echo $contact->getCity(); ?></td>
                          <td><?php echo $contact->getPhone(); ?></td>
                          <td><a class="workaround" href="<?php echo \App::getBaseUrl(); ?>contact/view/id/<?php echo $contact->getId(); ?>">Übersicht</a></td>
                          <td><a class="workaround" href="<?php echo \App::getBaseUrl(); ?>contact/edit/id/<?php echo $contact->getId(); ?>">Bearbeiten</a></td>
                          <td><a class="workaround" href="<?php echo \App::getBaseUrl(); ?>contact/delete/id/<?php echo $contact->getId(); ?>">Löschen</a></td>
                      </tr>
                  <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <!-- Kontaktnübersicht -->
        <div class="button-row">
            <a href="<?= \App::getBaseUrl(); ?>contact/new" class="button">Neuer Kontakt</a>
        </div>
    </body>
</html>
