<header>
    <h1>Project-Planner</h1>
</header>
<div>
    <form action="<?php echo \App::getBaseUrl(); ?>contact/add" method="post">
        <br>
        <div>
            <h2>Kontakt</h2>
        </div>
        <div>
            <label for="name">Kontakt:</label>
            <input type="text" name="name" value="<?php echo $contact->getName(); ?>" id="name">
        </div>
        <div>
            <label for="firstname">Vorname:</label>
            <input type="text" name="firstname" value="<?php echo $contact->getFirstname(); ?>" id="firstname">
            <label for="lastname">Nachname:</label>
            <input type="text" name="lastname" value="<?php echo $contact->getLastname(); ?>" id="lastname">
        </div>
        <div>
            <label for="city">Ort:</label>
            <input type="text" name="city" value="<?php echo $contact->getCity(); ?>" id="city">
        </div>
        <div>
            <label for="phone">Telefon:</label>
            <input type="text" name="phone" value="<?php echo $contact->getPhone(); ?>" id="phone">
        </div>
        <div>
            <label for="email">Email:</label>
            <input type="email" name="email" value="" id="email">
        </div>
        <div class="container">
            <!-- Projektübersicht -->
            <div class="projects">
                <h2>Projektübersicht</h2><hr>
                <table>
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Projektname</th>
                            <th>Begin</th>
                            <th>Ende</th>
                            <th>Status</th>
                            <th>Erstellt am</th>
                            <th colspan="3">Aktionen</th>
                        </tr>
                    </thead>
                    <tbody>
                      <?php foreach($projects as $project): ?>
                          <tr>
                              <td><?php echo $project->getId(); ?></td>
                              <td><?php echo $project->getTitle(); ?></td>
                              <td><?php echo $project->getBegin(); ?></td>
                              <td><?php echo $project->getEnd(); ?></td>
                              <td><?php echo $project->getStatus(); ?></td>
                              <td><?php echo $project->getCreatedAt(); ?></td>
                              <td><a class="workaround" href="#">Übersicht</a></td>
                              <td><a class="workaround" href="#">Bearbeiten</a></td>
                              <td><a class="workaround" href="#">Löschen</a></td>
                          </tr>
                      <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <!-- Projektübersicht -->
            <!-- Aufgabenübersicht -->
            <div class="tasks">
                <h2>Aufgabenübersicht</h2><hr>
                <table>
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Titel</th>
                            <th>Begin</th>
                            <th>Ende</th>
                            <th>Status</th>
                            <th colspan="3">Aktionen</th>
                        </tr>
                    </thead>
                    <tbody>
                      <?php foreach($tasks as $task): ?>
                          <tr>
                              <td><?php echo $task->getId(); ?></td>
                              <td><?php echo $task->getTitle(); ?></td>
                              <td><?php echo $task->getBegin(); ?></td>
                              <td><?php echo $task->getEnd(); ?></td>
                              <td><?php echo $task->getStatus(); ?></td>
                              <td><a class="workaround" href="#">Übersicht</a></td>
                              <td><a class="workaround" href="#">Bearbeiten</a></td>
                              <td><a class="workaround" href="#">Löschen</a></td>
                          </tr>
                      <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <!-- Aufgabenübersicht -->
        </div>
        <div class="button-row">
            <button type="submit" class="button">Speichern</button>&nbsp;&nbsp;
            <button type="submit" class="button">Bearbeiten</button>&nbsp;&nbsp;
            <button type="submit" class="button">Löschen</button>
            <button type="submit" class="button">Abbrechen</button>
        </div>
    </form>
</div>
