<header>
    <h1>Project-Planner</h1>
</header>
<!-- Kontaktübersicht -->
<div>
    <h2>Kontaktübersicht</h2>
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Firma</th>
                <th>Ansprechpartner</th>
                <th>Ort</th>
                <th>Telefon</th>
                <th colspan="2">Aktionen</th>
            </tr>
        </thead>
        <tbody>
          <?php foreach($contacts as $contact): ?>
              <tr>
                  <td><?php echo $contact->getId(); ?></td>
                  <td><?php echo $contact->getName(); ?></td>
                  <td><?php echo $contact->getFirstname() . '&nbsp;'
                    . $contact->getLastname(); ?></td>
                  <td><?php echo $contact->getCity(); ?></td>
                  <td><?php echo $contact->getPhone(); ?></td>
                  <td><a class="workaround" href="<?php echo \App::getBaseUrl(); ?>contact/view/id/<?php echo $contact->getId(); ?>">Übersicht</a></td>
                  <td><a class="workaround" href="<?php echo \App::getBaseUrl(); ?>contact/edit/id/<?php echo $contact->getId(); ?>">Bearbeiten</a></td>
              </tr>
          <?php endforeach; ?>
        </tbody>
    </table>
</div>
<!-- Kontaktnübersicht -->
<div class="button-row">
    <a href="<?= \App::getBaseUrl(); ?>contact/new" class="button">Neuer Kontakt</a>
</div>
