<!DOCTYPE html>
<html lang="de">
    <head>
        <meta charset="utf8">
        <title>Hauptseite</title>
        <link href="http://projektmanager.localhost/skin/css/style.css" rel="stylesheet">
    </head>
    <body>
        <header>
            <h1>Project-Planner</h1>
        </header>
        <nav>
            <ul>
                <li><a href="http://projektmanager.localhost/index/mainpage">Home</a></li>
                <li><a href="http://projektmanager.localhost/customer/index">Kunden</a></li>
                <li><a href="http://projektmanager.localhost/project/index">Projekte</a></li>
                <li><a href="http://projektmanager.localhost/task/index">Aufgaben</a></li>
            </ul>
        </nav>
        <!-- Kundenübersicht -->
        <div>
            <p class="overview">Kundenübersicht</p>
            <table>
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Firma</th>
                        <th>Ansprechpartner</th>
                        <th>Ort</th>
                        <th>Telefon</th>
                        <th colspan="3">Aktionen</th>
                    </tr>
                </thead>
                <tbody>
                  <?php foreach($customers as $customer): ?>
                      <tr>
                          <td><?php echo $customer->getId(); ?></td>
                          <td><?php echo $customer->getName(); ?></td>
                          <td><?php echo $customer->getFirstname() . '&nbsp;'
                            . $customer->getLastname(); ?></td>
                          <td><?php echo $customer->getCity(); ?></td>
                          <td><?php echo $customer->getPhone(); ?></td>
                          <td><a class="workaround" href="http://projektmanager.localhost/customer/view/id/<?php echo $customer->getId(); ?>">Übersicht</a></td>
                          <td><a class="workaround" href="http://projektmanager.localhost/customer/edit/id/<?php echo $customer->getId(); ?>">Bearbeiten</a></td>
                          <td><a class="workaround" href="http://projektmanager.localhost/customer/delete/id/<?php echo $customer->getId(); ?>">Löschen</a></td>
                      </tr>
                  <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <!-- Kundenübersicht -->
        <ul>
            <li><a href="http://projektmanager.localhost/customer/new">Neuer Kunde</a></li>
        </ul>
    </body>
</html>
