<nav>
    <ul class="pp-nav" role="navigation">
        <li class="header">Project-Planner</li>

        <?php if(\Session\User::isLoggedIn()): ?>

        <li><a href="<?= \App::getBaseUrl(); ?>index/main">Dashboard</a></li>
        <li><a href="<?= \App::getBaseUrl(); ?>contact/index">Kontakte</a></li>
        <li><a href="<?= \App::getBaseUrl(); ?>project/index">Projekte</a></li>
        <li><a href="<?= \App::getBaseUrl(); ?>task/index">Aufgaben</a></li>
        <li><a href="<?= \App::getBaseUrl(); ?>index/logout">Abmelden</a></li>

        <?php else: ?>

        <li><a href="<?= \App::getBaseUrl(); ?>index/login">Anmelden</a></li>

        <?php endif; ?>

    </ul>
</nav>
