<!DOCTYPE html>
<html lang="de">
    <head>
        <meta charset="utf8">
        <title>Hauptseite</title>
        <link href="<?php echo \App::getBaseUrl(); ?>skin/css/style.css" rel="stylesheet">
        <script type="text/javascript" src="<?php echo \App::getBaseUrl(); ?>skin/js/lib/jquery-3.3.1.min.js"></script>
        <script type="text/javascript" src="<?php echo \App::getBaseUrl(); ?>skin/js/tables.js"></script>
    </head>
    <body>
