<!DOCTYPE html>
<html lang="de">
    <head>
        <meta charset="utf8">
        <title>Hauptseite</title>
        <link href="<?php echo \App::getBaseUrl(); ?>skin/css/style.css" rel="stylesheet">
    </head>
    <body>
        <header>
            <h1>Project-Planner</h1>
        </header>
        <nav>
            <ul>
                <li><a href="<?php echo \App::getBaseUrl(); ?>index/main">Home</a></li>
                <li><a href="<?php echo \App::getBaseUrl(); ?>contact/index">Kontakte</a></li>
                <li><a href="<?php echo \App::getBaseUrl(); ?>project/index">Projekte</a></li>
                <li><a href="<?php echo \App::getBaseUrl(); ?>task/index">Aufgaben</a></li>
            </ul>
        </nav>
        <div>
            <form method="post">
                <br>
                <div>
                    <h2>Neue Aufgabe</h2>
                </div>
                <div>
                    <label for="title">Titel:</label>
                    <input type="text" name="name" id="title">
                </div>
                <div>
                    <label for="contact">Kontakt:</label>
                    <select id="contact">
                        <option>Bitte wählen ...</option>
                        <option>digital-connect GmbH</option>
                        <option>Max Mustermann GmbH</option>
                        <option>Atomkraftwerk Springfield</option>
                        <option>Washington Museum</option>
                    </select>
                <div>
                    <label for="contact">Projekt:</label>
                    <select id="contact">
                        <option>Bitte wählen ...</option>
                        <option>Probearbeit</option>
                    </select>
                </div>
                <div>
                    <label for="desc">Beschreibung:</label>
                    <textarea name="desc" id="desc"></textarea>
                </div>
                <div>
                    <label for="begin">Anfang:</label>
                    <input type="text" name="begin" id="begin">
                    <label for="end">Ende:</label>
                    <input type="text" name="end" id="end">
                </div>
                <div>
                    <label for="status">Status:</label>
                    <select id="status">
                        <option>aktiv</option>
                        <option>beendet</option>
                    </select>
                </div>
                <button>Anlegen</button>
                <button>Abbrechen</button>
            </form>
        </div>
    </body>
</html>
