<div>
    <form method="post">
        <br>
        <div>
            <h2>Neue Aufgabe</h2>
        </div>
        <div>
            <label for="title">Titel:</label>
            <input type="text" name="name" id="title">
        </div>
        <div>
            <label for="contact">Kontakt:</label>
            <select id="contact">
                <option>Bitte wählen ...</option>
                <option>digital-connect GmbH</option>
                <option>Max Mustermann GmbH</option>
                <option>Atomkraftwerk Springfield</option>
                <option>Washington Museum</option>
            </select>
        <div>
            <label for="contact">Projekt:</label>
            <select id="contact">
                <option>Bitte wählen ...</option>
                <option>Probearbeit</option>
            </select>
        </div>
        <div>
            <label for="desc">Beschreibung:</label>
            <textarea name="desc" id="desc"></textarea>
        </div>
        <div>
            <label for="begin">Anfang:</label>
            <input type="text" name="begin" id="begin">
            <label for="end">Ende:</label>
            <input type="text" name="end" id="end">
        </div>
        <div>
            <label for="status">Status:</label>
            <select id="status">
                <option>aktiv</option>
                <option>beendet</option>
            </select>
        </div>
        <div class="button-row">
        <button type="submit" class="button">Anlegen</button>
        <button type="submit" class="button">Abbrechen</button>
    </form>
</div>
