<div class="container">
    <!-- Kontaktnübersicht -->
    <div>
        <div>
            <h2>Kontaktübersicht
                <span class="element-pos-right"><a class="button-light" href="<?= \App::getBaseUrl(); ?>contact/new" title="Neuen Kontakt anlegen.">+</a></span>
                <hr>
            </h2>
        </div>
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th class="contact">Kontakt</th>
                    <th class="contactpartner">Ansprechpartner</th>
                    <th>Ort</th>
                    <th>Telefon</th>
                    <th>Email</th>
                    <th colspan="2" class="th_action">Aktionen</th>
                </tr>
            </thead>
            <tbody>
              <?php foreach($contacts as $contact): ?>
                  <tr class="clickable-row" data-href="<?= \App::getBaseUrl(); ?>contact/view/id/<?= $contact->getId(); ?>">
                      <td><?= $contact->getId(); ?></td>
                      <td><?= $contact->getName(); ?></td>
                      <td><?= $contact->getFirstname() . '&nbsp;'
                        . $contact->getLastname(); ?></td>
                      <td><?= $contact->getCity(); ?></td>
                      <td><?= $contact->getPhone(); ?></td>
                      <td>-</td>
                      <td class="action-button"><a href="<?= \App::getBaseUrl(); ?>contact/edit/id/<?= $contact->getId(); ?>">Bearbeiten</a></td>
                  </tr>
              <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <!-- -->
    <!-- Projektübersicht -->
    <div>
        <div>
            <h2>Projektübersicht
                <span class="element-pos-right"><a class="button-light" href="<?= \App::getBaseUrl(); ?>project/new" title="Neues Projekt anlegen">+</a></span>
                <hr>
            </h2>
        </div>
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Projektname</th>
                    <th>Begin</th>
                    <th>Ende</th>
                    <th>Status</th>
                    <th>Priorität</th>
                    <th>Fortschritt</th>
                    <th>Erstellt am</th>
                    <th colspan="2" class="th_action">Aktionen</th>
                </tr>
            </thead>
            <tbody id="projects-table">
              <?php foreach($projects as $project): ?>
                  <tr class="clickable-row" data-href="<?= \App::getBaseUrl(); ?>project/view/id/<?= $project->getId(); ?>">
                      <td><?= $project->getId(); ?></td>
                      <td><?= $project->getTitle(); ?></td>
                      <td class="td_begin"><?= $project->getBegin(); ?></td>
                      <td class="td_end"><?= $project->getEnd(); ?></td>
                      <td class="td_status"><?= $project->getStatus(); ?></td>
                      <td class="td_priority"><?= $project->getPriority(); ?></td>
                      <td>-</td>
                      <td class="td_createdAt"><?= $project->getCreatedAt(); ?></td>
                      <td class="action-button"><a href="<?= \App::getBaseUrl(); ?>project/edit/id/<?= $project->getId(); ?>">Bearbeiten</a></td>
                  </tr>
              <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <!-- Projekte -->
    <!-- Aufgabenübersicht -->
    <div>
        <div>
            <h2>Aufgabenübersicht
                <span class="element-pos-right"><a class="button-light" href="<?= \App::getBaseUrl(); ?>task/new" title="Neue Aufgabe anlegen.">+</a></span>
                <hr>
            </h2>
        </div>
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Titel</th>
                    <th>Projekt</th>
                    <th class="td_begin">Begin</th>
                    <th class="td_end">Ende</th>
                    <th class="td_status">Status</th>
                    <th>Priorität</th>
                    <th colspan="3" class="th_action">Aktionen</th>
                </tr>
            </thead>
            <tbody id="tasks-table">
              <?php foreach($tasks as $task): ?>
                  <tr class="clickable-row" data-href="<?= \App::getBaseUrl(); ?>task/view/id/<?= $task->getId(); ?>">
                      <td><?= $task->getId(); ?></td>
                      <td><?= $task->getTitle(); ?></td>
                      <td><?= $task->getProjectTitle(1); ?></td>
                      <td><?= $task->getBegin(); ?></td>
                      <td><?= $task->getEnd(); ?></td>
                      <td><?= $task->getStatus(); ?></td>
                      <td class="td_priority"><?= $task->getPriority(); ?></td>
                      <td class="action-button"><a href="<?= \App::getBaseUrl(); ?>task/edit/id/<?= $task->getId(); ?>">Bearbeiten</a></td>
                  </tr>
              <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <!-- Aufgabenübersicht -->
</div>
