<!DOCTYPE html>
<html lang="de">
    <head>
        <meta charset="utf8">
        <title>Hauptseite</title>
        <link href="<?php echo \App::getBaseUrl(); ?>skin/css/style.css" rel="stylesheet">
    </head>
    <body>
        <nav>
            <ul class="navigation">
                <li><a href="<?php echo \App::getBaseUrl(); ?>index/main">Home</a></li>
                <li><a href="<?php echo \App::getBaseUrl(); ?>contact/index">Kontakte</a></li>
                <li><a href="<?php echo \App::getBaseUrl(); ?>project/index">Projekte</a></li>
                <li><a href="<?php echo \App::getBaseUrl(); ?>task/index">Aufgaben</a></li>
                <li>
                    <?php if(\Session\User::isLoggedIn()): ?>
                        <a href="<?php echo \App::getBaseUrl(); ?>index/login">Sign out</a>
                    <?php else: ?>
                        <a href="<?php echo \App::getBaseUrl(); ?>index/login">Sign in</a>
                    <?php endif; ?>
                </li>
            </ul>
        </nav>
        <header>
            <h1 class="project-title">Project-Planner</h1>
        </header>
        <!-- Kontaktnübersicht -->
        <div>
            <h2>Kontaktübersicht</h2>
            <table>
                <thead>
                    <tr>
                        <th>#</th>
                        <th class="contact">Kontakt</th>
                        <th class="contactpartner">Ansprechpartner</th>
                        <th>Ort</th>
                        <th>Telefon</th>
                        <th colspan="3">Aktionen</th>
                    </tr>
                </thead>
                <tbody>
                  <?php foreach($contacts as $contact): ?>
                      <tr>
                          <td><?php echo $contact->getId(); ?></td>
                          <td><?php echo $contact->getName(); ?></td>
                          <td><?php echo $contact->getFirstname() . '&nbsp;'
                            . $contact->getLastname(); ?></td>
                          <td><?php echo $contact->getCity(); ?></td>
                          <td><?php echo $contact->getPhone(); ?></td>
                          <td><a class="workaround" href="#">Übersicht</a></td>
                          <td><a class="workaround" href="#">Bearbeiten</a></td>
                          <td><a class="workaround" href="#">Löschen</a></td>
                      </tr>
                  <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <!-- -->
        <!-- Projektübersicht -->
        <div>
            <h2>Projektübersicht</h2>
            <table>
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Projektname</th>
                        <th>Begin</th>
                        <th>Ende</th>
                        <th>Status</th>
                        <th>Erstellt am</th>
                        <th colspan="3">Aktionen</th>
                    </tr>
                </thead>
                <tbody>
                  <?php foreach($projects as $project): ?>
                      <tr>
                          <td><?php echo $project->getId(); ?></td>
                          <td><?php echo $project->getTitle(); ?></td>
                          <td><?php echo $project->getBegin(); ?></td>
                          <td><?php echo $project->getEnd(); ?></td>
                          <td><?php echo $project->getStatus(); ?></td>
                          <td><?php echo $project->getCreatedAt(); ?></td>
                          <td><a class="workaround" href="#">Übersicht</a></td>
                          <td><a class="workaround" href="#">Bearbeiten</a></td>
                          <td><a class="workaround" href="#">Löschen</a></td>
                      </tr>
                  <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <!-- Projekte -->
        <!-- Aufgabenübersicht -->
        <div>
            <h2>Aufgabenübersicht</h2>
            <table>
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Titel</th>
                        <th>Begin</th>
                        <th>Ende</th>
                        <th>Status</th>
                        <th colspan="3">Aktionen</th>
                    </tr>
                </thead>
                <tbody>
                  <?php foreach($tasks as $task): ?>
                      <tr>
                          <td><?php echo $task->getId(); ?></td>
                          <td><?php echo $task->getTitle(); ?></td>
                          <td><?php echo $task->getBegin(); ?></td>
                          <td><?php echo $task->getEnd(); ?></td>
                          <td><?php echo $task->getStatus(); ?></td>
                          <td><a class="workaround" href="#">Übersicht</a></td>
                          <td><a class="workaround" href="#">Bearbeiten</a></td>
                          <td><a class="workaround" href="#">Löschen</a></td>
                      </tr>
                  <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <!-- Aufgabenübersicht -->
    </body>
</html>
