<nav>
    <ul class="pp-nav" role="navigation">
        <li><a href="<?php echo \App::getBaseUrl(); ?>index/main">Dashboard</a></li>
        <li><a href="<?php echo \App::getBaseUrl(); ?>contact/index">Kontakte</a></li>
        <li><a href="<?php echo \App::getBaseUrl(); ?>project/index">Projekte</a></li>
        <li><a href="<?php echo \App::getBaseUrl(); ?>task/index">Aufgaben</a></li>
        <li>
            <?php if(\Session\User::isLoggedIn()): ?>
                <a href="<?php echo \App::getBaseUrl(); ?>index/login">Abmelden</a>
            <?php else: ?>
                <a href="<?php echo \App::getBaseUrl(); ?>index/login">Anmelden</a>
            <?php endif; ?>
        </li>
    </ul>
</nav>
