<!DOCTYPE html>
<html lang="de">
    <head>
        <meta charset="utf8">
        <title>Hauptseite</title>
        <link href="<?= \App::getBaseUrl(); ?>/skin/css/style.css" rel="stylesheet">
    </head>
    <body>
        <nav>
            <ul class="navigation">
                <li><a href="<?= \App::getBaseUrl(); ?>index/main">Home</a></li>
                <li><a href="<?= \App::getBaseUrl(); ?>contact/index">Kontakte</a></li>
                <li><a href="<?= \App::getBaseUrl(); ?>project/index">Projekte</a></li>
                <li><a href="<?= \App::getBaseUrl(); ?>task/index">Aufgaben</a></li>
                <li>
                    <?php if(\Session\User::isLoggedIn()): ?>
                        <a href="<?= \App::getBaseUrl(); ?>index/login">Sign out</a>
                    <?php else: ?>
                        <a href="<?= \App::getBaseUrl(); ?>index/login">Sign in</a>
                    <?php endif; ?>
                </li>
            </ul>
        </nav>
        <header>
            <h1 class="project-title">Project-Planner</h1>
        </header>
        <!-- Projektübersicht -->
        <div>
            <h2>Projektübersicht</h2>
            <table>
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Projektname</th>
                        <th>Begin</th>
                        <th>Ende</th>
                        <th>Status</th>
                        <th>Erstellt am</th>
                        <th colspan="3">Aktionen</th>
                    </tr>
                </thead>
                <tbody>
                  <?php foreach($projects as $project): ?>
                      <tr>
                          <td><?= $project->getId(); ?></td>
                          <td><?= $project->getTitle(); ?></td>
                          <td><?= $project->getBegin(); ?></td>
                          <td><?= $project->getEnd(); ?></td>
                          <td><?= $project->getStatus(); ?></td>
                          <td><?= $project->getCreatedAt(); ?></td>
                          <td><a href="<?php echo \App::getBaseUrl(); ?>project/view/id/<?= $project->getId(); ?>">Übersicht</a></td>
                          <td><a href="<?php echo \App::getBaseUrl(); ?>project/edit/id/<?= $project->getId(); ?>">Bearbeiten</a></td>
                          <td><a href="<?php echo \App::getBaseUrl(); ?>project/delete/id/<?= $project->getId(); ?>">Löschen</a></td>
                      </tr>
                  <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <!-- Projektübersicht -->
        <div class="button-row">
            <a class="button" href="<?= \App::getBaseUrl(); ?>project/new">Neues Projekt</a>
        </div>
    </body>
</html>
