<!DOCTYPE html>
<html lang="de">
    <head>
        <meta charset="utf8">
        <title>Hauptseite</title>
        <link href="<?php echo \App::getBaseUrl(); ?>skin/css/style.css" rel="stylesheet">
    </head>
    <body>
        <nav>
            <ul class="navigation">
                <li><a href="<?php echo \App::getBaseUrl(); ?>index/main">Start</a></li>
                <li><a href="<?php echo \App::getBaseUrl(); ?>contact/index">Kontakte</a></li>
                <li><a href="<?php echo \App::getBaseUrl(); ?>project/index">Projekte</a></li>
                <li><a href="<?php echo \App::getBaseUrl(); ?>task/index">Aufgaben</a></li>
                <li>
                    <?php if(\Session\User::isLoggedIn()): ?>
                        <a href="<?php echo \App::getBaseUrl(); ?>index/login">Sign out</a>
                    <?php else: ?>
                        <a href="<?php echo \App::getBaseUrl(); ?>index/login">Sign in</a>
                    <?php endif; ?>
                </li>
            </ul>
        </nav>
        <header>
            <h1>Project-Planner</h1>
        </header>
        <div>
            <form action="<?php echo \App::getBaseUrl(); ?>project/add" method="post">
                <br>
                <div>
                    <h2>Neues Projekt</h2>
                </div>
                <div>
                    <label for="name">Titel:</label>
                    <input type="text" name="title" id="name">
                </div>
                <div>
                    <label for="contact">Kontakt:</label>
                    <select id="contact" name="contactId">
                        <?php foreach ($contacts as $contact): var_dump($contact);?>
                        <option value="<?php echo $contact->getId(); ?>"><?= $contact->getFirstname() . ' ' . $contact->getLastname(); ?></option>
                        <?php endforeach; ?>
                    </select>
                <div>
                    <label for="contact">Ansprechp.:</label>
                    <input type="text" name="contactPerson" id="name">
                </div>
                <div>
                    <label for="desc">Beschreibung:</label>
                    <textarea name="desc" id="desc"></textarea>
                </div>
                <div>
                    <label for="begin">Anfang:</label>
                    <input type="date" name="begin" id="begin">
                    <label for="end">Ende:</label>
                    <input type="date" name="end" id="end">
                </div>
                <div>
                    <label for="status">Status:</label>
                    <select id="status" name="status">
                        <option value="active">aktiv</option>
                        <option value="inactive">beendet</option>
                    </select>
                </div>
                <div class="button-row">
                    <button type="submit" class="button">Anlegen</button>
                    <button type="submit" class="button">Abbrechen</button>
                </div>
            </form>
        </div>
    </body>
</html>
