<header>
    <h1 class="project-title">Project-Planner</h1>
</header>
<!-- Projektübersicht -->
<div>
    <h2>Projektübersicht</h2>
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Projektname</th>
                <th>Begin</th>
                <th>Ende</th>
                <th>Status</th>
                <th>Erstellt am</th>
                <th colspan="2">Aktionen</th>
            </tr>
        </thead>
        <tbody>
          <?php foreach($projects as $project): ?>
              <tr>
                  <td><?= $project->getId(); ?></td>
                  <td><?= $project->getTitle(); ?></td>
                  <td><?= $project->getBegin(); ?></td>
                  <td><?= $project->getEnd(); ?></td>
                  <td><?= $project->getStatus(); ?></td>
                  <td><?= $project->getCreatedAt(); ?></td>
                  <td><a href="<?php echo \App::getBaseUrl(); ?>project/view/id/<?= $project->getId(); ?>">Übersicht</a></td>
                  <td><a href="<?php echo \App::getBaseUrl(); ?>project/edit/id/<?= $project->getId(); ?>">Bearbeiten</a></td>
              </tr>
          <?php endforeach; ?>
        </tbody>
    </table>
</div>
<!-- Projektübersicht -->
<div class="button-row">
    <a class="button" href="<?= \App::getBaseUrl(); ?>project/new">Neues Projekt</a>
</div>
