<div><br>
	<h2>Projektübersicht</h2>
</div>
<div>
	<label for="name">Titel:</label>
	<span><?= $project->getTitle(); ?></span>
</div>
<div>
	<label for="contact">Kontakt:</label>
	<span><?= $contact->getName(); ?></span>
</div>
<div>
	<label for="contact">Ansprechp.:</label>
	<span><?= $contact->getFirstname() . '&nbsp;' . $contact->getLastname(); ?></span>
</div>
<div>
	<label for="desc">Beschreibung:</label>
	<span><?= $project->getDesc(); ?></span>
</div>
<div>
	<label for="begin">Anfang:</label>
	<span><?= $project->getBegin(); ?></span>
	<label for="end">Ende:</label>
	<span><?= $project->getEnd(); ?></span>
</div>
<div>
	<label for="status">Status:</label>
	<span><?= $project->getStatus(); ?></span>
</div>
<div class="button-row">
	<a class="button" href="<?= \App::getBaseUrl(); ?>project/edit/id/<?= $project->getId(); ?>">Bearbeiten</a>
</div>
<!-- Aufgabenübersicht -->
<div>
	<div>
		<h2>Aufgabenübersicht
			<span class="element-pos-right"><a class="button-light" href="<?= \App::getBaseUrl(); ?>task/new/id/<?= $project->getId(); ?>" title="Neue Aufgabe anlegen.">+</a></span>
			<hr>
		</h2>
	</div>
	<table>
		<thead>
			<tr>
				<th>#</th>
				<th>Titel</th>
				<th>Begin</th>
				<th>Ende</th>
				<th>Status</th>
				<th>Priorität</th>
				<th>Fortschritt</th>
				<th colspan="3">Aktionen</th>
			</tr>
		</thead>
		<tbody id="tasks-table">
			<?php foreach($tasks as $task): ?>
			<tr class="clickable-row" data-href="<?= \App::getBaseUrl(); ?>task/view/id/<?= $task->getId(); ?>">
				<td><?= $task->getId(); ?></td>
				<td><?= $task->getTitle(); ?></td>
				<td class="td_begin"><?= $task->getBegin(); ?></td>
				<td class="td_end"><?= $task->getEnd(); ?></td>
				<td class="td_status"><?= $task->getStatus(); ?></td>
				<td class="td_priority"><?= $task->getPriority(); ?></td>
				<td>-</td>
				<td><a href="<?= \App::getBaseUrl(); ?>task/edit/id/<?= $task->getId(); ?>">Bearbeiten</a></td>
			</tr>
			<?php endforeach; ?>
	   </tbody>
	</table>
</div>
