<div>
    <h2>Projektübersicht</h2>
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Projektname</th>
                <th>Begin</th>
                <th>Ende</th>
                <th>Status</th>
                <th>Fortschritt</th>
                <th>Erstellt am</th>
                <th colspan="2">Aktionen</th>
            </tr>
        </thead>
        <tbody id="projects-table">
          <?php foreach($projects as $project): ?>
              <tr class="clickable-row" data-href="<?= \App::getBaseUrl(); ?>project/view/id/<?= $project->getId(); ?>">
                  <td><?= $project->getId(); ?></td>
                  <td><?= $project->getTitle(); ?></td>
                  <td><?= $project->getBegin(); ?></td>
                  <td><?= $project->getEnd(); ?></td>
                  <td><?= $project->getStatus(); ?></td>
                  <td>-</td>
                  <td><?= $project->getCreatedAt(); ?></td>
                  <td><a href="<?= \App::getBaseUrl(); ?>project/edit/id/<?= $project->getId(); ?>">Bearbeiten</a></td>
              </tr>
          <?php endforeach; ?>
        </tbody>
    </table>
</div>
<div class="button-row">
    <a class="button" href="<?= \App::getBaseUrl(); ?>project/new">Neues Projekt</a>
</div>
