<!DOCTYPE html>
<html lang="de">
	<head>
		<meta charset="utf8">
		<title>Hauptseite</title>
		<link href="<?php echo \App::getBaseUrl(); ?>skin/css/style.css" rel="stylesheet">
	</head>
	<body>
		<nav>
            <ul class="navigation">
                <li><a href="<?php echo \App::getBaseUrl(); ?>index/main">Start</a></li>
                <li><a href="<?php echo \App::getBaseUrl(); ?>contact/index">Kontakte</a></li>
                <li><a href="<?php echo \App::getBaseUrl(); ?>project/index">Projekte</a></li>
                <li><a href="<?php echo \App::getBaseUrl(); ?>task/index">Aufgaben</a></li>
                <li>
                    <?php if(\Session\User::isLoggedIn()): ?>
                        <a href="<?php echo \App::getBaseUrl(); ?>index/login">Sign out</a>
                    <?php else: ?>
                        <a href="<?php echo \App::getBaseUrl(); ?>index/login">Sign in</a>
                    <?php endif; ?>
                </li>
            </ul>
        </nav>
    	<header>
    		<h1 class="project-title">Project-Planner</h1>
    	</header>
		<div><br>
			<h2>Projektübersicht</h2>
		</div>
		<div>
			<label for="name">Titel:</label>
			<input type="text" value="<?php echo $project->getTitle(); ?>" id="name" disabled>
		</div>
		<div>
			<label for="contact">Kontakt:</label>
			<input type="text" value="<?php echo $contact->getName(); ?>" id="contact" disabled>
		</div>
		<div>
			<label for="contact">Ansprechp.:</label>
			<input type="text" value="<?php echo $contact->getFirstname() . '&nbsp;' . $contact->getLastname(); ?>" id="name" disabled>
		</div>
		<div>
			<label for="desc">Beschreibung:</label>
			<textarea id="desc" disabled><?php echo $project->getDesc(); ?>"</textarea>
		</div>
		<div>
			<label for="begin">Anfang:</label>
			<input type="text" value="<?php echo $project->getBegin(); ?>" id="begin">
			<label for="end">Ende:</label>
			<input type="text" value="<?php echo $project->getEnd(); ?>" id="end">
		</div>
		<div>
			<label for="status">Status:</label>
			<input type="text" value="<?php echo $project->getStatus(); ?>" id="name" disabled>
		</div>
		<!-- Aufgabenübersicht -->
		<div>
			<div>
				<h2>Aufgabenübersicht
					<span class="element-pos-right"><a class="button-light" href="<?= \App::getBaseUrl(); ?>contact/new" title="Neuen Kontakt anlegen.">+</a></span>
                    <hr>
				</h2>
			</div>
			<table>
				<thead>
					<tr>
						<th>#</th>
						<th>Titel</th>
						<th>Begin</th>
						<th>Ende</th>
						<th>Status</th>
						<th colspan="3">Aktionen</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach($tasks as $task): ?>
                    <tr>
						<td><?php echo $task->getId(); ?></td>
						<td><?php echo $task->getTitle(); ?></td>
						<td><?php echo $task->getBegin(); ?></td>
						<td><?php echo $task->getEnd(); ?></td>
						<td><?php echo $task->getStatus(); ?></td>
						<td><a href="<?= \App::getBaseUrl(); ?>project/view/id/<?= $project->getId(); ?>">Übersicht</a></td>
						<td><a href="<?= \App::getBaseUrl(); ?>project/edit/id/<?= $project->getId(); ?>">Bearbeiten</a></td>
						<td><a href="<?= \App::getBaseUrl(); ?>task/delete/id/<?= $task->getId(); ?>">Löschen</a></td>
					</tr>
                    <?php endforeach; ?>
               </tbody>
		</table>
		</div>
		<!-- Aufgabenübersicht -->
		<div class="button-row">
			<button class="button">Anlegen</button>
			<button class="button">Abbrechen</button>
		</div>
	</body>
</html>
