<div><br>
	<h2>Projektübersicht</h2>
</div>
<div>
	<label for="name">Titel:</label>
	<input type="text" value="<?= $project->getTitle(); ?>" id="name" disabled>
</div>
<div>
	<label for="contact">Kontakt:</label>
	<input type="text" value="<?= $contact->getName(); ?>" id="contact" disabled>
</div>
<div>
	<label for="contact">Ansprechp.:</label>
	<input type="text" value="<?= $contact->getFirstname() . '&nbsp;' . $contact->getLastname(); ?>" id="name" disabled>
</div>
<div>
	<label for="desc">Beschreibung:</label>
	<textarea id="desc" disabled><?= $project->getDesc(); ?></textarea>
</div>
<div>
	<label for="begin">Anfang:</label>
	<input type="datetime-local" value="<?= $project->getBegin(); ?>" id="begin" disabled>
	<label for="end">Ende:</label>
	<input type="datetime-local" value="<?= $project->getEnd(); ?>" id="end" disabled>
</div>
<div>
	<label for="status">Status:</label>
	<input type="text" value="<?= $project->getStatus(); ?>" id="name" disabled>
</div>
<!-- Aufgabenübersicht -->
<div>
	<div>
		<h2>Aufgabenübersicht
			<span class="element-pos-right"><a class="button-light" href="<?= \App::getBaseUrl(); ?>task/new" title="Neue Aufgabe anlegen.">+</a></span>
			<hr>
		</h2>
	</div>
	<table>
		<thead>
			<tr>
				<th>#</th>
				<th>Titel</th>
				<th>Begin</th>
				<th>Ende</th>
				<th>Status</th>
				<th>Priorität</th>
				<th>Fortschritt</th>
				<th colspan="3">Aktionen</th>
			</tr>
		</thead>
		<tbody id="tasks-table">
			<?php foreach($tasks as $task): ?>
			<tr class="clickable-row" data-href="<?= \App::getBaseUrl(); ?>task/view/id/<?= $task->getId(); ?>">
				<td><?= $task->getId(); ?></td>
				<td><?= $task->getTitle(); ?></td>
				<td><?= $task->getBegin(); ?></td>
				<td><?= $task->getEnd(); ?></td>
				<td><?= $task->getStatus(); ?></td>
				<td>-</td>
				<td>-</td>
				<td><a href="<?= \App::getBaseUrl(); ?>task/edit/id/<?= $task->getId(); ?>">Bearbeiten</a></td>
			</tr>
			<?php endforeach; ?>
	   </tbody>
</table>
</div>
