<header>
    <h1>Project-Planner</h1>
</header>
<!-- Aufgabenübersicht -->
<div>
    <h2>Aufgabenübersicht</h2>
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Titel</th>
                <th>Begin</th>
                <th>Ende</th>
                <th>Status</th>
                <th colspan="3">Aktionen</th>
            </tr>
        </thead>
        <tbody>
          <?php foreach($tasks as $task): ?>
              <tr>
                  <td><?= $task->getId(); ?></td>
                  <td><?= $task->getTitle(); ?></td>
                  <td><?= $task->getBegin(); ?></td>
                  <td><?= $task->getEnd(); ?></td>
                  <td><?= $task->getStatus(); ?></td>
                  <td><a href="#">Übersicht</a></td>
                  <td><a href="#">Bearbeiten</a></td>
                  <td><a href="#">Löschen</a></td>
              </tr>
          <?php endforeach; ?>
        </tbody>
    </table>
</div>
<!-- Aufgabenübersicht -->
<div class="button-row">
    <a href="<?php echo App::getBaseUrl();?>task/new" class="button">Neue Aufgabe</a>
</ul>
