<!DOCTYPE html>
<html lang="de">
    <head>
        <meta charset="utf8">
        <title>Hauptseite</title>
        <link href="<?php echo \App::getBaseUrl(); ?>skin/css/style.css" rel="stylesheet">
    </head>
    <body>
        <header>
            <h1>Project-Planner</h1>
        </header>
        <nav>
            <ul>
                <li><a href="<?php echo \App::getBaseUrl(); ?>index/main">Home</a></li>
                <li><a href="<?php echo \App::getBaseUrl(); ?>customer/index">Kunden</a></li>
                <li><a href="<?php echo \App::getBaseUrl(); ?>project/index">Projekte</a></li>
                <li><a href="<?php echo \App::getBaseUrl(); ?>task/index">Aufgaben</a></li>
            </ul>
        </nav>
        <div>
            <form action="<?php echo \App::getBaseUrl(); ?>task/add" method="post">
                <br>
                <div>
                    <h2>Neue Aufgabe</h2>
                </div>
                <div>
                    <label for="name">Titel:</label>
                    <input type="text" name="title" id="name">
                </div>
                <div>
                    <label for="customer">Kunde:</label>
                    <select id="customer" name="customerId">
                        <?php foreach ($customers as $customer): ?>
                        <option value="<?php echo $customer->getId(); ?>"><?php echo $customer->getName(); ?></option>
                        <?php endforeach; ?>
                    </select>
                <div>
                    <label for="project">Projekt.:</label>
                    <select id="customer" name="projectId">
                        <?php foreach ($projects as $project): ?>
                        <option value="<?php echo $project->getId(); ?>"><?php echo $project->getTitle(); ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div>
                    <label for="desc">Beschreibung:</label>
                    <textarea name="desc" id="desc"></textarea>
                </div>
                <div>
                    <label for="begin">Anfang:</label>
                    <input type="date" name="begin" id="begin">
                    <label for="end">Ende:</label>
                    <input type="date" name="end" id="end">
                </div>
                <div>
                    <label for="status">Status:</label>
                    <select id="status" name="status">
                        <option value="active">aktiv</option>
                        <option value="inactive">beendet</option>
                    </select>
                </div>
                <button type="submit">Anlegen</button>
                <button>Abbrechen</button>
            </form>
        </div>
    </body>
</html>
