<div>
    <h2>Aufgabenübersicht</h2>
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Titel</th>
                <th>Projekt</th>
                <th>Begin</th>
                <th>Ende</th>
                <th>Status</th>
                <th>Priorität</th>
                <th>Fortschritt</th>
                <th colspan="3">Aktionen</th>
            </tr>
        </thead>
        <tbody id="tasks-table">
          <?php foreach($tasks as $task): ?>
              <tr class="clickable-row" data-href="<?= \App::getBaseUrl(); ?>task/view/id/<?= $task->getId(); ?>">
                  <td><?= $task->getId(); ?></td>
                  <td><?= $task->getTitle(); ?></td>
                  <td>-</td>
                  <td><?= $task->getBegin(); ?></td>
                  <td><?= $task->getEnd(); ?></td>
                  <td><?= $task->getStatus(); ?></td>
                  <td><?= $task->getPriority(); ?></td>
                  <td>-</td>
                  <td class="action-button"><a href="<?= \App::getBaseUrl(); ?>task/edit/id/<?= $task->getId(); ?>">Bearbeiten</a></td>
              </tr>
          <?php endforeach; ?>
        </tbody>
    </table>
</div>
<div class="button-row">
    <a href="<?php echo App::getBaseUrl();?>task/new" class="button">Neue Aufgabe</a>
</ul>
