<!DOCTYPE html>
<html lang="de">
    <head>
        <meta charset="utf8">
        <title>Hauptseite</title>
        <link href="<?php echo \App::getBaseUrl(); ?>skin/css/style.css" rel="stylesheet">
    </head>
    <body>
        <nav>
            <ul class="navigation">
                <li><a href="<?php echo \App::getBaseUrl(); ?>index/main">Start</a></li>
                <li><a href="<?php echo \App::getBaseUrl(); ?>contact/index">Kontakte</a></li>
                <li><a href="<?php echo \App::getBaseUrl(); ?>project/index">Projekte</a></li>
                <li><a href="<?php echo \App::getBaseUrl(); ?>task/index">Aufgaben</a></li>
                <li>
                    <?php if(\Session\User::isLoggedIn()): ?>
                        <a href="<?php echo \App::getBaseUrl(); ?>index/login">Sign out</a>
                    <?php else: ?>
                        <a href="<?php echo \App::getBaseUrl(); ?>index/login">Sign in</a>
                    <?php endif; ?>
                </li>
            </ul>
        </nav>
        <header>
            <h1>Project-Planner</h1>
        </header>
        <!-- Aufgabenübersicht -->
        <div>
            <h2>Aufgabenübersicht</h2>
            <table>
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Titel</th>
                        <th>Begin</th>
                        <th>Ende</th>
                        <th>Status</th>
                        <th colspan="3">Aktionen</th>
                    </tr>
                </thead>
                <tbody>
                  <?php foreach($tasks as $task): ?>
                      <tr>
                          <td><?= $task->getId(); ?></td>
                          <td><?= $task->getTitle(); ?></td>
                          <td><?= $task->getBegin(); ?></td>
                          <td><?= $task->getEnd(); ?></td>
                          <td><?= $task->getStatus(); ?></td>
                          <td><a href="#">Übersicht</a></td>
                          <td><a href="#">Bearbeiten</a></td>
                          <td><a href="#">Löschen</a></td>
                      </tr>
                  <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <!-- Aufgabenübersicht -->
        <div class="button-row">
            <a href="<?php echo App::getBaseUrl();?>task/new" class="button">Neue Aufgabe</a>
        </ul>
    </body>
</html>
