<!DOCTYPE html>
<html lang="de">
    <head>
        <meta charset="utf8">
        <title>Hauptseite</title>
        <link href="http://projektmanager.localhost/skin/css/style.css" rel="stylesheet">
    </head>
    <body>
        <header>
            <h1>Project-Planner</h1>
        </header>
        <nav>
            <ul>
                <li><a href="http://projektmanager.localhost/index/mainpage">Home</a></li>
                <li><a href="http://projektmanager.localhost/customer/index">Kunden</a></li>
                <li><a href="http://projektmanager.localhost/project/index">Projekte</a></li>
                <li><a href="http://projektmanager.localhost/task/index">Aufgaben</a></li>
            </ul>
        </nav>
        <!-- Aufgabenübersicht -->
        <div>
            <p class="overview">Aufgabenübersicht</p>
            <table>
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Titel</th>
                        <th>Beschreibung</th>
                        <th>Begin</th>
                        <th>Ende</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                  <?php foreach($tasks as $task): ?>
                      <tr>
                          <td><?php echo $task->getId(); ?></td>
                          <td><?php echo $task->getTitle(); ?></td>
                          <td><?php echo $task->getDesc(); ?></td>
                          <td><?php echo $task->getBegin(); ?></td>
                          <td><?php echo $task->getEnd(); ?></td>
                          <td><?php echo $task->getStatus(); ?></td>
                      </tr>
                  <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <!-- Aufgabenübersicht -->
        <ul>
            <li><a href="#">Neue Aufgabe</a></li>
        </ul>
    </body>
</html>
